services:
  client_service:
    build: .
    command: ["python", "vpn_client.py"]
    cap_add:
      - NET_ADMIN
    networks: 
      - northtunnel_network

  server_service:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8888:8888/udp" 
    command: ["python", "vpn_server.py"]
    cap_add:
      - NET_ADMIN
    networks:
      - northtunnel_network

networks:
  northtunnel_network: